In [2]:
from transformers import BertForNextSentencePrediction, BertTokenizer

In [3]:
import torch

In [5]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
bert_nsp = BertForNextSentencePrediction.from_pretrained('bert-base-uncased')

In [6]:
bert_nsp

BertForNextSentencePrediction(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, element

In [7]:
text = "Deliver huge improvements to your machine learning pipelines without spending hours fine-tuning parameters"
text2 = "This book's practical case-studies reveal feature engineering techniques that upgrade your data-wrangling"

In [8]:
inputs = tokenizer(text,text2,return_tensors='pt')

In [9]:
inputs

{'input_ids': tensor([[  101,  8116,  4121,  8377,  2000,  2115,  3698,  4083, 13117,  2015,
          2302,  5938,  2847,  2986,  1011, 17372, 11709,   102,  2023,  2338,
          1005,  1055,  6742,  2553,  1011,  2913,  7487,  3444,  3330,  5461,
          2008, 12200,  2115,  2951,  1011, 23277,  5654,  2989,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [10]:
inputs.input_ids

tensor([[  101,  8116,  4121,  8377,  2000,  2115,  3698,  4083, 13117,  2015,
          2302,  5938,  2847,  2986,  1011, 17372, 11709,   102,  2023,  2338,
          1005,  1055,  6742,  2553,  1011,  2913,  7487,  3444,  3330,  5461,
          2008, 12200,  2115,  2951,  1011, 23277,  5654,  2989,   102]])

In [11]:
inputs.token_type_ids

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [12]:
inputs.attention_mask

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [14]:
# 0 == 'isNextSentence' and 1 == 'notNextSentence'
outputs = bert_nsp(**inputs)

In [15]:
outputs

NextSentencePredictorOutput(loss=None, logits=tensor([[ 6.2143, -5.8919]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [16]:
# calculate loss by passing through a label
outputs = bert_nsp(**inputs, labels = torch.LongTensor([0]))
outputs

NextSentencePredictorOutput(loss=tensor(5.4836e-06, grad_fn=<NllLossBackward0>), logits=tensor([[ 6.2143, -5.8919]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [17]:
# calculate loss by passing through a label
outputs = bert_nsp(**inputs, labels = torch.LongTensor([1]))
outputs

NextSentencePredictorOutput(loss=tensor(12.1063, grad_fn=<NllLossBackward0>), logits=tensor([[ 6.2143, -5.8919]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [18]:
# Model was quite sure that text2 is the next sentence of text